Repository Akshatchaube01/TimeWarp, pull requests merged in 2024-07, with the labels that each got.

#351 fixed the chat bot styling
  src/components/Chatbot.jsx
  src/components/chatbot.css
Labels: gssoc, level1

#356 Removed the extra portion of the navbar and aligned it
  src/components/Navbar.jsx
Labels: gssoc, level1

#358 Fixed UI bugs.
  src/components/AboutUs.css
  src/components/ContactUs.jsx
  src/components/Home.jsx
  src/components/Navbar.jsx
Labels: gssoc, level3

#361 Made chatbot more conversational
  src/utils/actionProvider.js
  src/utils/messageParser.js
Labels: gssoc, level2

#363 Added New "Cursor-Trail Effect" to The Website
  index.html
  src/main.css
  src/main.jsx
  trail.js
Labels: gssoc, level2

#368 Website load enhancement
  src/App.jsx
  src/main.jsx
Labels: gssoc, level1

#386 Hide the "Trail effect" in Mobile view
  index.html
Labels: gssoc, level1
