Repository Akshatchaube01/TimeWarp, pull requests merged in 2024-05, with the labels that each got.

#55 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: GSSoC'24, Level1

#66 Update Models.css
  src/components/Models.css
Labels: GSSoC'24, Level1

#67 Added icons
  src/components/Navbar.jsx
Labels: GSSoC'24, Level1

#73 redirect to email and dialer pad added
  src/components/ContactUs.jsx
Labels: GSSoC'24, Level1

#77 fix-#76: About Section Background Issue Resolved.
  src/components/Particles.jsx
Labels: GSSoC'24, Level1

#87 Create pull-request.md
  .github/pull-request.md
Labels: GSSoC'24, Level1

#89 Fix:Improved navbar UI on mobile phones.
  package-lock.json
  src/components/Navbar.jsx
Labels: GSSoC'24, Level1

#91 Fix demopage responsive
  src/components/DemoSection.css
  src/components/DemoSection.jsx
Labels: GSSoC'24, Level1

#94 Create LICENSE
  LICENSE
Labels: GSSoC'24, Level1

#120 moved HamburgerMenu to right in mobile
  src/components/Navbar.jsx
Labels: gssoc, level1

#134 Added Custom 404 page
  src/assets/bg.jpg
  src/assets/logo.png
  src/components/Custom404.jsx
  src/main.jsx
  tailwind.config.js
Labels: gssoc, level2

#140 Fixed Issue #132
  README.md
Labels: gssoc, level1

#121 worked on contact page
  src/components/ContactUs.jsx
Labels: gssoc, level1

#154 fixed the responsiveness issue on the nav bar
  backend/.env
  src/components/Navbar.jsx
Labels: gssoc, level1

#158 Recommended places using user's current location and unsplash api
  index.html
  src/components/ComparePlaces.jsx
  src/components/Models.jsx
  src/components/RecommendedPlaces.jsx
Labels: gssoc, level2

#171 nav animation is done
  src/components/Navbar.jsx
Labels: gssoc, level1

#178 Major design Update in footer
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/ThemeToggle.jsx
Labels: gssoc, level2

#180 frost glass cards have been added
  src/components/AboutUs.jsx
Labels: gssoc, level1

#181 Twitter logo updated #168
  src/components/Footer.jsx
Labels: gssoc, level1
