Repository Akshatchaube01/TimeWarp, pull requests merged in 2024-06, with the labels that each got.

#195 Fixed Contact Us Page Responding to Theme Change
  src/components/ContactUs.jsx
Labels: gssoc, level1

#198 Home is now not visible in mobile responsiveness
  src/components/Navbar.css
  src/components/Navbar.jsx
Labels: gssoc, level1

#200 Bugfix: Email sending successful with alert message
  .env
  package-lock.json
  package.json
  src/components/ContactUs.jsx
  vite.config.js
Labels: gssoc, level2

#201 Fixed Issue #185
  src/components/Footer.css
  src/components/Unsplash.jsx
Labels: gssoc, level1

#202 feat: Update README.md
  README.md
Labels: gssoc, level1

#214 Changed the cursor color and added dynamic background.
  package-lock.json
  package.json
  src/components/AboutUs.jsx
  src/components/AnimatedBackground.jsx
  src/components/ContactUs.jsx
  src/components/DemoSection.css
  src/components/DemoSection.jsx
  src/components/FireFlies.jsx
  src/components/Models.jsx
  src/main.jsx
Labels: gssoc, level3

#227 Solved the issue of page reloading when theme is switched
  src/components/ThemeToggle.jsx
Labels: gssoc, level2

#234 added contact us with extra info
  src/components/ContactUs.jsx
Labels: gssoc, level2

#242 Terms Page Added
  src/assets/terms.png
  src/components/Privacy.jsx
  src/components/Terms.jsx
  src/components/terms.css
  src/main.jsx
Labels: gssoc, level3

#248 added footer links -- company section
  src/components/Footer.jsx
Labels: gssoc, level1

#250 Disable text selection on home page, fixes #245
  src/components/Home.css
  src/components/Typewriter.jsx
Labels: gssoc, level1

#259 animated the icons in demosection
  package-lock.json
  package.json
  src/components/Chatbot.jsx
  src/components/DemoSection.css
  src/components/DemoSection.jsx
  src/components/chatbot.css
  src/main.css
  src/main.jsx
  src/utils/actionProvider.js
  src/utils/config.js
  src/utils/messageParser.js
Labels: gssoc, level3

#261 Changed PA surname
  src/utils/config.js
Labels: gssoc, level1

#264 added title in mobile
  src/components/Navbar.jsx
Labels: gssoc, level1

#285 Added the web3 forms
  src/components/ContactUs.jsx
Labels: gssoc, level3

#125 Added issue template for documentation issues
  .github/ISSUE_TEMPLATE/documentation.md
Labels: gssoc, level1

#289 chatbot responsive
  src/components/chatbot.css
Labels: gssoc, level1

#293 Made the Quote in the footer to change every 10 secs and also everytime site is reloaded
  src/components/Footer.jsx
Labels: gssoc, level2

#294 Added Preloader
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Preloader.json
  src/components/Home.jsx
  src/components/Preloader.css
  src/components/Preloader.jsx
  src/main.jsx
Labels: gssoc, level2

#311 footer ui in about us
  src/components/Footer.css
Labels: gssoc, level1

#128 Added the feature of auto commenting when a PR is merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: gssoc, level1

#314 Added email validation
  src/components/ContactUs.jsx
Labels: gssoc, level1

#312 added all contributors
  package-lock.json
  src/components/AboutUs.css
  src/components/AboutUs.jsx
Labels: gssoc, level3

#319 Fixed the about us and contact us Ui
  src/components/AboutUs.jsx
  src/components/ContactUs.jsx
Labels: gssoc, level2

#322 Tilt effect to privacy policy and terms and conditions page
  src/components/Privacy.jsx
  src/components/Terms.jsx
Labels: gssoc, level1

#325 worked on issue #101 -Linking our Team cards to Linkedin
  package-lock.json
  package.json
  src/components/AboutUs.jsx
Labels: gssoc, level1

#324 Added Google Translator in footer
  index.html
  src/components/Footer.jsx
Labels: gssoc, level2

#327 Added Licensing Page Reflecting MIT License to Website Footer
  src/components/Footer.jsx
  src/components/licensing.css
  src/components/licensing.jsx
  src/main.jsx
Labels: gssoc, level1

#329 add share icon
  src/components/Models.css
  src/components/Models.jsx
Labels: gssoc, level1

#336 Made "Chatbot" is "Responsive"
  src/components/chatbot.css
Labels: gssoc, level1

#341 Fixed Contributor List Prematurely Resets During Slide Animation
  src/components/AboutUs.css
  src/components/AboutUs.jsx
Labels: gssoc, level1

#349 Updated Interests.css
  src/components/Interests.css
Labels: gssoc, level1
